# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT} # Project root directory

# path to data directory
data_dir: ${oc.env:DATASET_PATH} # Dataset root directory
training_metadata_db_path: ${oc.env:TRAINING_METADATA_DB_PATH} # Path to training metadata db file
validation_metadata_db_path: ${oc.env:VALIDATION_METADATA_DB_PATH} # Path to validation metadata db file
evaluation_metadata_db_path: ${oc.env:EVALUATION_METADATA_DB_PATH} # Path to evaluation metadata db file

# path to logging directory
log_dir: ${paths.root_dir}/logs/ # Logging directory

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir} # Hydra output directory

# path to working directory
work_dir: ${hydra:runtime.cwd} # Working directory at runtime
