# https://www.tensorflow.org/tensorboard/

tensorboard: # TensorBoard logger config
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger # Logger class
  save_dir: "${paths.output_dir}/tensorboard/" # Output directory
  name: null # Run name
  log_graph: False # Log model graph
  default_hp_metric: True # Log default hparams metric
  prefix: "" # Metric key prefix
  # version: ""
