# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.EarlyStopping.html

early_stopping: # Early stopping callback config
  _target_: lightning.pytorch.callbacks.EarlyStopping # Callback class
  monitor: ??? # Quantity to be monitored, must be specified
  min_delta: 0. # Minimum change to qualify as improvement
  patience: 3 # Checks with no improvement before stopping
  verbose: False # Verbosity mode
  mode: "min" # Optimization direction: min or max
  strict: True # Error if monitored metric is missing
  check_finite: True # Stop if metric becomes NaN/inf
  stopping_threshold: null # Stop once metric reaches this threshold
  divergence_threshold: null # Stop once metric becomes worse than this threshold
  check_on_train_epoch_end: null # Run on train epoch end when set
  # log_rank_zero_only: False  # this keyword argument isn't available in stable version
