# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.RichProgressBar.html

rich_progress_bar: # Rich progress bar callback config
  _target_: utils.safe_progress_bar.SafeRichProgressBar # Callback class
