sync_semantic_evaluation:
  _target_: src.utils.callbacks.sync_semantic_evaluation.SyncSemanticEvaluation
  enabled: true
  eval_config_name: eval
  eval_overrides: []
  every_n_train_steps: 10000
  direct_scalar_logging: true
  log_media: true
  fail_on_error: true
  start_index: 1
  stop_index: 48
  max_samples: null
