# @package _global_

# default debugging setup, runs 1 full epoch
# other debugging configs can inherit from this one

# overwrite task name so debugging logs are stored in separate folder
task_name: "debug" # Run name for debug outputs

# disable callbacks and loggers during debugging
callbacks: null # Disable callbacks for debugging
logger: null # Disable loggers for debugging

extras: # Debug overrides for extras
  ignore_warnings: False # Keep warnings visible
  enforce_tags: False # Skip tag enforcement

# sets level of all command line loggers to 'DEBUG'
# https://hydra.cc/docs/tutorials/basic/running_your_app/logging/
hydra: # Hydra logging overrides
  job_logging: # Hydra job logging settings
    root: # Root logger settings
      level: DEBUG # Verbose logging level

  # use this to also set hydra loggers to 'DEBUG'
  # verbose: True

trainer: # Trainer overrides for debugging
  max_epochs: 1 # Short debug run
  accelerator: cpu # Debuggers don't like GPUs
  devices: 1 # Avoid multiprocessing
  detect_anomaly: true # Raise if NaN or inf detected

data: # DataLoader overrides for debugging
  num_workers: 0 # Avoid multiprocessing
  pin_memory: False # Disable GPU memory pin
