defaults:
  - default

strategy:
  _target_: lightning.pytorch.strategies.DeepSpeedStrategy
  _convert_: all
  config:
    checkpoint:
      load_universal: ${ds_universal}
    bf16:
      enabled: true
    communication_data_type: fp32
    zero_optimization:
      stage: 2
      allgather_partitions: true
      allgather_bucket_size: 5e8
      reduce_bucket_size: 5e8
    wall_clock_breakdown: false